<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conf</string>
		<string>conf.erb</string>
		<string>conf.template</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\{$</string>
	<key>foldingStopMarker</key>
	<string>\}$</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Sphinx Conf</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i)\b(indexer|searchd|source|index)</string>
			<key>name</key>
			<string>keyword.other.sphinx</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.sphinx</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b([\w\d_]+)</string>
			<key>name</key>
			<string>meta.language.section.sphinx</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\{</string>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?i)\b\$(start|end)</string>
					<key>name</key>
					<string>variable.other.start-stop.sphinx</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.options.sphinx</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.value.sphinx</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*([^#]*)=(.*)$</string>
					<key>name</key>
					<string>meta.config.option.sphinx</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#embedded</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#embedded</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.sphinx</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*#.*\n?</string>
					<key>name</key>
					<string>comment.line.number-sign.sphinx</string>
				</dict>
			</array>
		</dict>
		<key>embedded</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>&lt;%(=|-)?</string>
					<key>end</key>
					<string>-?%&gt;</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i)\bsql_query[\w_]*\s+=</string>
					<key>end</key>
					<string>[^\\]\n$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.sql</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.sphinx</string>
	<key>uuid</key>
	<string>0DB6EF41-B776-44CC-B9F6-185A49EA672A</string>
</dict>
</plist>
